- lib/index.js
> Call captureStackTrace to filter boom from traces

- README.md
- lib/index.js
- test/index.js
This resolves hapijs/boom#74 by adding `Boom.preconditionRequired`.
> Support Precondition Required

- lib/index.js
- test/index.js
> Fix ctor passing in serverError helper

- README.md
- lib/index.js
- test/index.js
> Cleanup for 254593fd1d09e79049692675a4f9b7b5108b36d8

- README.md
- lib/index.js
- test/index.js
> Rename serverTimeout to serverUnavailable

- README.md
I followed the [Joi API doc example](https://github.com/hapijs/joi/blob/v9.0.4/API.md#anyinvalidvalue---aliases-disallow-not) and added `internal` as an alias for `badImplementation` since the returned `statusCode` and `error` are the same.
> Add Boom.internal() to API docs fixes #127

- README.md
- lib/index.js
- test/index.js
Closes https://github.com/hapijs/boom/issues/132.
This PR adds an optional `allow` parameter to `Boom.methodNotAllowed`, which in turn sets the "Allow" header on the output, [as required in the spec](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.6). It accepts either a string or an array of strings to be combined and comma-separated.
> Add 'allow' parameter to methodNotAllowed for setting 'Allow' header

- README.md
- lib/index.js
- test/index.js
Here is small PR for issue #146.
> Unauthorized extension for #146

- lib/index.js
- test/index.js
Hey guys,
This may be a special use case, but it makes for nice filtering of errors without having to deep check vs strings and numbers.
Although it doesn't satisfy the instanceof concern as seen here https://github.com/hapijs/boom/issues/101, it does make filtering manually cleaner.
Instead of having to do such things as:
```
import boom from "boom";
const err = boom.notFound("Something is not found");
if (err.isBoom && err.output.statusCode === 404) return; // true;
if (err.isBoom && err.output.payload.statusCode === 404) return; // true;
if (err.isBoom && err.output.payload.error === "Not Found") return; // true;
```
You can instead do:
```
import boom from "boom";
const err = boom.notFound("Something is not found");
if (err.isBoom && err.typeOf(boom.notFound)) return; // true;
``` …
> Added typeOf functionality

- README.md
This is more in line with the code.
I had a case where I called `Boom.bommify(err)` on a boom error with statusCode 401 expecting it to convert to a 500.
> docs(readme): clarified `boomify` statusCode default option

- lib/index.d.ts
- test/index.ts
Fixes #237
This fixes the types, but it's a little concerning that the tests didn't catch this. It seems they don't actually run the code? 
@jarrodyellets 
@hueniverse   
>  error TS2551: Property 'serverUnavailable' does not exist on type 'typeof Boom'. Did you mean 'serviceUnavailable'?
> Fix types: serviceUnavailable -> serverUnavailable.

- lib/index.d.ts
- test/index.ts
https://www.typescriptlang.org/docs/handbook/advanced-types.html#typeof-type-guards
@hueniverse
> Fix types: Update static isBoom to be a type guard.

- API.md
- lib/index.d.ts
- lib/index.js
- test/index.js
- test/index.ts
Hi! I read that the status 425 code refers to `Too Early` so I made this small contribution if you don't mind.
References:
* [RFC 8470](https://tools.ietf.org/html/rfc8470#section-5.2)
* [MDN: 425 Too Early](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/425)
> Add HTTP code 425 Too Early

- API.md
- lib/index.d.ts
- lib/index.js
- test/index.js
Thank you again for this great library, I'm very happy to contribute to [hapi](https://github.com/hapijs) projects :slightly_smiling_face: 
In this humble PR, I wanted to resolve #265.
> Add optional statusCode parameter to Boom.isBoom

- API.md
Boom is not a constructor, so trying to call `new Boom` will generate a TypeError.  This PR updates the documentation to illustrate the correct way of creating a new Boom error.
> Update/Clarify documentation for creating new Boom.

- API.md
The `instanceof` check needs to be called with `Boom.Boom` since `Boom` is not a constructor. Calling `err instanceof Boom` throws `TypeError: Right-hand side of 'instanceof' is not callable`
> Docs: Clarify usage with `instanceof`

- lib/index.d.ts
- test/index.ts
Especially useful in hapijs context, where request.response can be a
Boom object. This change allows the TypeScript code to leverage isBoom()
to check if request.response is a Boom object or not, without any noisy typecast.
> Make isBoom type definition laxer

- lib/index.d.ts
- test/index.ts
> TypeScript: Allow custom properties on output.payload

- lib/index.d.ts
- test/index.ts
`object` doesn't allow properly looking up values on `headers` (for example, `headers['Authorization']` will be rejected by Typescript). Using `Partial<Record<string, string>>` allows this lookup and accounts for potentially undefined headers.
> Add proper index type to headers property

- lib/index.js
- test/index.js
This should fix the false positives reported in #285. Now any `instanceof` check called on a `Boom` subclass will effectively return `false`, since the actual returned object from the constructor is _never_ a `Boom` object.
I used https://stackoverflow.com/a/57898482/248062 as input.
> Don't mess with instanceof checks called on subclasses
